version: '3'
services:
    php-apache:
        build:
            context: .
            dockerfile: ./docker-php-apache/Dockerfile
        ports:
            - 8080:80
            - 8443:443
        # env_file: ./docker-php-apache/php-apache.env
        env_file: './apache.env'
        depends_on:
            - 'mysql'
        links:
            - 'mysql:database'
        stdin_open: true # docker run -i
        tty: true   
        volumes:
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
        - type: bind 
          source: /home/USER/Hacienda/
          target: /var/www/html/files/

    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        env_file: './mariadb.env'
        ports:
        - '4407:3306'
        volumes: 
        - "./db.sql:/docker-entrypoint-initdb.d/db.sql"
        - "data:/var/lib/mysql"
        tty: true
volumes:
  data:
  hacienda: