ERROR_BAD_REQUEST = -1
ERROR_ERROR = -2
SUCCESS_ALL_GOOD = 1

ERROR_USERS_NO_VALID = -300
ERROR_USERS_WRONG_LOGIN_INFO = -301
ERROR_USERS_NO_VALID_SESSION = -302
ERROR_USERS_ACCESS_DENIED = -303
ERROR_USERS_EXISTS = -304
ERROR_USERS_NO_TOKEN = -302

ERROR_FILES_TOO_BIG = -400
ERROR_FILES_NOT_ALLOWED = -401
ERROR_FILES_UPLOAD_ERROR = -402
ERROR_FILES_DOWNLOAD_ERROR = -403
ERROR_FILES_EXT_NOT_ALLOWED = -404
ERROR_FILES_NOT_FOUND = -405
